#! /bin/sh

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# present working directory
DIR=$(dirname $(readlink -e $0)) ;

echo "\nUbuntu System Setup\n"

# gets sudo rights
sudo -v > /dev/null

printf "\nThis install process will switch your default shell to zsh as well as make some other changes.\nDo you wish to continue? [Y/n]: "
read CONTINUE
CONTINUE=$(echo $CONTINUE | tr 'a-z' 'A-Z')


# enables shell option for no case matching in strings
# 
# to disable this:
#   shopt -u nocasematch
# shopt -s nocasematch

if [ "$CONTINUE" = 'N' ] || [ "$CONTINUE" = 'NO' ]; then
    echo "Exiting!"
    exit 1
fi

printf "\nIs this being install on desktop with a desktop manager (gnome, unity, kde etc)?\nNo if server [Y/n]: "

read DESK
DESK=$(echo $DESK | tr 'a-z' 'A-Z')

echo ""

if [ "$DESK" = 'Y' ] || [ "$DESK" = 'YES' ] || [ -z $DESK ]; then

    log_daemon_msg "Installing packages ..."
        # sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn
    # install appropriate packages
        sudo apt-get -y update > /dev/null
        # sudo apt-get -y install trash-cli mutt centerim vim git tmux multitail ack-grep nodejs nodejs-legacy zsh tilda terminology > /dev/null
    log_end_msg 0

fi

exit 1

# copies over asset imgs and such
log_daemon_msg "Copying assets..."
    mkdir -p ~/.icons > /dev/null
    cp "$DIR/imgs/ubuntu-logo-basic.svg" ~/.icons > /dev/null
    cp "$DIR/imgs/ubuntu-logo-tilt-256.png" ~/.icons /dev/null
log_end_msg 0

# goes through and executes each install script
log_daemon_msg "Setting up bashrc submodule ..."
    /bin/sh/ "$DIR/bashrc/install" > /dev/null
    echo `source ~/.bashrc` > /dev/null
log_end_msg 0

# downloads install script for oh-my-zsh plugin
log_daemon_msg "Setting up oh-my-zsh ..."
    wget --no-check-certificate http://install.ohmyz.sh -O - | sh /dev/null
log_end_msg 0

# changes default shell from /bin/bash to /bin/zsh (
log_daemon_msg "Setting zsh as default shell ..."
    chsh -s $(which zsh) > /dev/null
log_end_msg 0

# sets up zsh
log_daemon_msg "Setting up zshrc submodule ..."
    /bin/sh "$DIR/zshrc/install" > /dev/null
log_end_msg 0


log_daemon_msg "Changing shell to zsh ..."
    zsh > /dev/null
    echo `source ~/.zshrc` > /dev/null
log_end_msg 0


# Setups up VIM settings
log_daemon_msg "Setting up VIM ..."
    mkdir ~/.vim > /dev/null # creates dir
    ln -s ~/.vimrc "$DIR/vim/vimrc" > /dev/null
log_end_msg 0

# seting zsh-autcomplete
log_daemon_msg "Setting up zsh-autosuggestions ..."
    /bin/sh "$DIR/zsh-autosuggestions/install" > /dev/null
log_end_msg 0

echo "\nSuccess: System setup complete!"

exit 0
