#!/bin/sh
# use this for a startup script to set primary monitor
#
# xrandr --query
# - will provide list of monitors
#
# Note: You can permanently set this in ~/.config/monitors.xml

xrandr --output HDMI1 --primary
