#!/bin/bash

. ./scripts/vars

for D in `find submodules -mindepth 1 -maxdepth 1 -type d`
do
    if [ -d "$DIR/log/$LOGFILE" ]; then
        # REMV=$(dirname "$D")
        REPLACE=''
        # MODNAME="${D/$REMV/$REPLACE}"
        MODNAME=$D

        log_daemon_msg "Upgrading $MODNAME ..."
        # cd $DIR/$D >> "$DIR/log/$LOGFILE"
        # git pull >> "$DIR/log/$LOGFILE"
        log_end_msg 0
    fi

done
