#!/bin/bash

. ./scripts/vars

log_daemon_msg "Fixing google chrome desktop launcher ..."
    
    # back up orig google-chrome.desktop
    sed '/[Desktop Entry]/a StartupWMClass=Google-chrome-stable' /usr/share/applications.google-chrome.desktop >> "$DIR/log/$LOGFILE"
    sed '/[NewWindow Shortcut Group]/a StartupWMClass=Google-chrome-stable' /usr/share/applications.google-chrome.desktop >> "$DIR/log/$LOGFILE"
    sed '/[NewIncognito Shortcut Group]/a StartupWMClass=Google-chrome-stable' /usr/share/applications.google-chrome.desktop >> "$DIR/log/$LOGFILE"

log_end_msg 0
