#!/bin/bash
# Run script when external monitor disconnects from device
# in this situation HDMI cord from laptop

#log tag
LT=HDMI

logger -i -t $LT "Setting resolution for eDP1"
if xrandr --output eDP1 --primary --mode 2160x1440 --output HDMI1 --off; then
    exit 0
else
    logger -i -t $LT "ERROR: Cannot turn off HDMI"
    exit 1
fi
