#!/bin/bash
# Run script when external monitor connects to computer
# in this situation HDMI cord into laptop (builtin display)

#log tag
LT=HDMI

logger -i -t $LT "Setting resolution for eDP1 and HDMI1"
if xrandr --output eDP1 --mode 2160x1440 --output HDMI1 --primary --mode 1920x1080 --right-of eDP1; then
    exit 0
else
    logger -is -t $LT "ERROR: Unable to set displays with xrandr"
    exit 1
fi
