#!/bin/bash

. ./scripts/vars

log_daemon_msg "Extracting assets and setting up Login screen  ..."

    # extracts the log file
    tar -zxf "$DIR/assets/gdm_themes/$THEMETAR" -C "$DIR/assets/gdm_themes" >> "DIR/log/$LOGFILE"

    #copy assets to proper locations
    sudo cp $DIR/assets/gdm_themes/nospeedlimit/chase.jpg /usr/share/backgrounds
    

    # installs 
    su - gdm -s /bin/bash
    # `dbus-launch | sed "s/^/export /"`
    # GSETTINGS_BACKEND=dconf gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/FILE.JPG"
    # GSETTINGS_BACKEND=dconf gsettings set org.gnome.desktop.interface gtk-theme ""

log_end_msg 0
