#!/bin/bash

. ./scripts/vars

# goes through and executes each install script
log_daemon_msg "Setting up bashrc submodule ..."
    sh "$DIR/bashrc/install" >> "$DIR/log/$LOGFILE"
    echo `source ~/.bashrc` >> "$DIR/log/$LOGFILE"
log_end_msg 0
