#!/bin/bash

. ./scripts/vars

# install appropriate packages
log_daemon_msg "Installing packages ..."

    # adds google linux repo
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

    # adds each PPA in PPA array var
    for P in PPA
    do
        # Adds PPA
        sudo add-apt-repository -y "$P" >> "$DIR/log/$LOGFILE"
    done

    # addds additional repos
    for src in SRCLIST
    do
        echo "$src" >> /etc/apt/sources.list
    done

    # updates apt
    sudo apt-get -y update >> "$DIR/log/$LOGFILE"

    # sudo apt-get -y install trash-cli mutt centerim vim git tmux multitail ack-grep nodejs nodejs-legacy zsh tilda terminology slim slidewall compiz-plugins-livewallpapers faience-theme >> "$DIR/log/$LOGFILE"
    sudo apt-get -y install $PKGS

    # set the splash page when booting - user must select it
    sudo update-alternatives --config default.plymouth >> "$DIR/log/$LOGFILE"
    sudo update-initramfs -u >> "$DIR/log/$LOGFILE"

log_end_msg 0
