#!/bin/bash

. ./scripts/vars

# install appropriate packages
log_daemon_msg "Installing packages ..."
    # sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn
    sudo apt-get -y update >> "$DIR/log/$LOGFILE"
    # sudo apt-get -y install trash-cli mutt centerim vim git tmux multitail ack-grep nodejs nodejs-legacy zsh tilda terminology slim >> "$DIR/log/$LOGFILE"
log_end_msg 0

