#!/bin/bash

. ./scripts/vars

# install appropriate packages
log_daemon_msg "Installing packages ..."
    sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn >> "$DIR/log/$LOGFILE"
    sudo add-apt-repository -y ppa:noobslab/apps >> "$DIR/log/$LOGFILE"
    sudo add-apt-repository -y ppa:tiheum/equinox >> "$DIR/log/$LOGFILE"

    sudo apt-get -y update >> "$DIR/log/$LOGFILE"
    PKGS = join \s PACKAGES
    # sudo apt-get -y install trash-cli mutt centerim vim git tmux multitail ack-grep nodejs nodejs-legacy zsh tilda terminology slim slidewall compiz-plugins-livewallpapers faience-theme >> "$DIR/log/$LOGFILE"
    sudo apt-get -y install $PKGS
log_end_msg 0
