#!/bin/bash

. ./scripts/vars

# use this for a startup script to set primary monitor
#
# xrandr --query
# - will provide list of monitors
#
# Note: You can permanently set this in ~/.config/monitors.xml

xrandr --output HDMI1 --primary >> "$DIR/log/$LOGFILE"

if hash docky 2> /dev/null; then
    DOCKY=$(echo $DOCKY | tr 'a-z' 'A-Z')

    pkill docky >> "$DIR/log/$LOGFILE"
    docky > /dev/null &
fi

