#!/bin/bash

# clears screen
clear

. ./scripts/vars
# PKGS = join , "$PACKAGES"
# echo "Pkgs:$PKGS"
# exit 1

# ensures log file has been created
touch "$DIR/log/$LOGFILE" > /dev/null

echo "\nUbuntu System Setup\n"

# gets sudo rights
sudo -v >> "$DIR/log/$LOGFILE"

$DIR/scripts/prompt_continue

printf "\nIs this being install on desktop with a desktop manager (gnome, unity, kde etc)?\nNo if server [Y/n]: "

read DESK

DESK=$(echo $DESK | tr 'a-z' 'A-Z')

echo ""

if [ "$DESK" = 'Y' ] || [ "$DESK" = 'YES' ] || [ -z $DESK ]; then
    ./scripts/upgrade_system
    ./scripts/install_packages
    # ./scripts/gdm
fi

exit 1

$DIR/scripts/copy_assets
#$DIR/scripts/install_bashrc
# $DIR/scripts/git_submodules
# $DIR/scripts/install_zsh
# $DIR/scripts/install_vim

echo "\nSuccess: System setup complete!"

exit 0
