#!/bin/bash

. ./scripts/vars

# upgrades the system
log_daemon_msg "Upgrading system ..."
    sudo apt-get -y update >> "$DIR/log/$LOGFILE"
    sudo apt-get -y upgrade >> "$DIR/log/$LOGFILE"
    sudo apt-get -y dist-upgrade >> "$DIR/log/$LOGFILE"
log_end_msg 0
