#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# Ubuntu's short release version name: trusty, utopic, etc..
REL=$(lsb_release -cs)

# Ubuntu's version number: 14.04, 14.10, 15.04 etc.
VER=$(lsb_release -sr)

THEMETAR='42735-nospeedlimit.tar.gz'
LOGFILE='install.log'
PPAFILE='ppa.log'
DM='gdm' # Default display manager
BG='ubuntu-sky.jpg' # /usr/share/backgrounds/
BGLOCK='cloud-flares.jpg' # /usr/share/gnome-shell/theme/
BGLOGIN='cloud-flares.jpg' #
THEME='Faience'
ICONS='fs-icons-ubuntu' # icon theme to be used
THEME='plymouth-theme-solar' # package name of plymouth splash screen

# PPA array to app-add-repository
#
# * Terminology.........ppa:hannes-janetzek/enlightenment-svn
# * TODO ...............ppa:noobslab/apps
# * faience-theme.......ppa:tiheum/equinox
# * fs-icons............ppa:noobslab/icons2
# * super-boot-manager..ppa:ingalex/super-boot-manager


PPA=(
    'ppa:hannes-janetzek/enlightenment-svn'
    'ppa:noobslab/apps'
    'ppa:tiheum/equinox'
    'ppa:noobslab/icons2'
    'ppa:ingalex/super-boot-manager'
    'ppa:dockbar-main/ppa'
    'ppa:teejee2008/ppa'
    'ppa:webupd8team/java'
)

PACKAGES=(
    'trash-cli'
    'mutt'
    'centerim'
    'vim'
    'git'
    'tmux'
    'multitail'
    'ack-grep'
    'nodejs'
    'nodejs-legacy'
    'zsh'
    'tilda'
    'terminology'
    'slim'
    'faience-theme'
    'plymouth-theme-solar'
    'npm'
    'docky'
    'awesome'
    'awesome-extra'
    'fs-icons'
    'conky-manager'
    'redshift'
    'oracle-java8-installer'
)


# Source List additions
#

SRCLIST=(
    "deb http://ppa.launchpad.net/docky-core/ppa/ubuntu $REL main"
    "deb-src http://ppa.launchpad.net/docky-core/ppa/ubuntu $REL main"
    "deb http://dl.google.com/linux/chrome/deb/ stable main"
)

# parent directory of /path/to/.ubuntu/scripts/vars </\--(YOU ARE HERE)
# which after the two DIR=* lines should be: /path/to/.ubuntu
DIR=$(dirname $(readlink -e $0))
DIR=$(dirname $(readlink -e $DIR))

# join array function
function join { local IFS="$1"; shift; echo "$*"; }
