#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# file name of tarball in assets/gdm_themes
THEMETAR='42735-nospeedlimit.tar.gz'
LOGFILE='install.log'

DIR=$(dirname $(readlink -e $0))
DIR=$(dirname $(readlink -e $DIR))
