#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

THEMETAR='42735-nospeedlimit.tar.gz'
LOGFILE='install.log'
DM='gdm' # Default display manager
BG='ubuntu-sky.jpg' # /usr/share/backgrounds/
BGLOCK='cloud-flares.jpg' # /usr/share/gnome-shell/theme/
BGLOGIN='cloud-flares.jpg' #
THEME='Faience'
ICONS='fs-icons-ubuntu' # icon theme to be used
THEME='plymouth-theme-solar' # package name of plymouth splash screen


PACKAGES=(
    "trash-cli"
    "mutt"
    "centerim"
    "vim"
    "git"
    "tmux"
    "multitail"
    "ack-grep"
    "nodejs"
    "nodejs-legacy"
    "zsh"
    "tilda"
    "terminology"
    "slim"
    "faience-theme"
    "plymouth-theme-solar"
    "npm"
    "docky"
    "fs-icons"
    "gnome-do"
    "gnome-do-plugins"
)

# parent directory of ~/.ubuntu/scripts/vars </\--(YOU ARE HERE)
# which after the two DIR=* lines should be: ~/.ubuntu
DIR=$(dirname $(readlink -e $0))
DIR=$(dirname $(readlink -e $DIR))

# Ubuntu's short release version name: trusty, utopic, etc..
REL=$(lsb_release -cs)

# join array function
function join { local IFS="$1"; shift; echo "$*"; }
